/* SI 413 Fall 2013
 * Lab 4
 * Hall, Micky S.
 * Flex file specifying the calculator program scanner
 */
%{
#include "calc.tab.hpp"
#include <cstdlib> // for atoi
%}

/* This tells flex to quit when it reaches EOF */
%option noyywrap

%%


[0-1]+(b) { yylval.val = strtol(yytext,NULL,2); return NUM;}
[0-9]+    { yylval.val = atoi(yytext); return NUM; }
[+-]      { yylval.sym = yytext[0]; return OPA; }
[*/]      { yylval.sym = yytext[0]; return OPM; }
[a-zA-Z0-9]+ { yylval.str = strdup(yytext); return NAME; }
["]+(.)*["]+ { }
":="      { return ASN; }
"@"       { return ACC;}
"#"(.)*   { }
"!"       { return SETACC; }
"("       { return LP; }
")"       { return RP; }
";b"      { return STOPB; }
";"       { return STOP; }
<<EOF>>   { return 0; }
[ \t\n]+  { }
.         { errout << "Unrecognized token starting with " << yytext[0] << endl; exit(1); }
%%
